version: '2'

services:
  node-backend:
    build: node-backend
    ports:
      - "3000:3000"
    links:
      - mongo-db

  vue-frontend:
    build: vue-frontend
    ports:
      - "8000:8000"

  mongo-db:
    image: mongo:latest
    ports:
    - "27017:27017"
